[[language]]
name = "rust"
auto-format = true
[language-server.ladybird]
command = "clangd"
args = ["--header-insertion=never"]

[[language]]
name = "cpp"
language-servers = ["ladybird"]
[language-server.astro-ls]
command = "astro-ls"
args = [ "--stdio" ]
config = { "typescript" = { "tsdk" = "/Users/ishankbg/Library/pnpm/global/5/node_modules/typescript/lib"}, "environment" = "node" }
[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]
[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true
[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]
[[language]]
name = "astro"
scope = "source.astro"
auto-format = true
injection-regex = "astro"
file-types = ["astro"]
roots = ["package.json"]
language-servers = [ "astro-ls", "tailwindcss-ls" ]
formatter = { command = "prettier", args = ["--parser", "astro"] }
[language-server.zls]
command = "/Users/ishankbg/lsp/zls"
